{
 "title": "My dashboard",
 "description": "Test",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Время задержки",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_request_duration_highr_seconds_bucket[5m])))",
     "legendFormat": "95% квантиль задержки"
    },
    {
     "expr": "sum(rate(http_request_duration_highr_seconds_sum[5m])) / sum(rate(http_request_duration_highr_seconds_count[5m]))",
     "legendFormat": "Среднее значение задержки"
    }
   ]
  },
  {
   "title": "Количество запросов",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_count{instance=\"fastapi_app:8000\", job=\"fastapi\", method=\"GET\"}[$__rate_interval])",
     "legendFormat": "{{handler}}"
    },
    {
     "expr": "rate(http_requests_total{status=\"5xx\"}[$__rate_interval])",
     "legendFormat": "{{handler}}/{{status}}"
    }
   ]
  },
  {
   "title": "Память",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "custom_memory_usage_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "custom_cpu_usage_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Общий трафик",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(custom_network_usage_bytes_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Статистика ошибок",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(handler, status) (rate(http_requests_total[$__rate_interval]))",
     "legendFormat": "{{handler}}:{{status}}"
    }
   ]
  },
  {
   "title": "Использование диска",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "custom_disk_usage_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Средний размер запроса",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(http_response_size_bytes_sum[5m])) / sum(rate(http_response_size_bytes_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Гистограмма предсказаний, количество/цена в руб",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by(le) (sum_over_time(price_predictions_bucket[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(http_request_duration_seconds_created)*1000",
     "legendFormat": "Start time"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - min(http_request_duration_seconds_created))",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "price_predictions_count", "legendFormat": "__auto" }
   ]
  }
 ]
}