services:
  fastapi:  
    env_file:
      - ./.env
    build:
      dockerfile: Dockerfile-stage-4
    ports:
      - "${APP_PORT}:${APP_PORT}"
    hostname: fastapi_app

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    hostname: prometheus 
  
  grafana:
    image: grafana/grafana
    env_file:
      - ./.env
    ports:
      - 3000:3000
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning        
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASS}