global:
  scrape_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'fastapi'
    metrics_path: /metrics
    scheme: http
    
    static_configs:
      - targets:
        - fastapi_app:8000